#!/usr/bin/env node

/* Copyright (c) 2015 - 2017 CoNWeT Lab., Universidad Politécnica de Madrid
 *
 * This file belongs to the Accounting Proxy
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

// Displays all the administrators for the specified service.

var program = require('commander'),
    config = require('./config'),
    logger = require('./log')
    util = require('./util');

var db = require(config.database.type);

program
    .description('Displays all the administrators for the specified service.')
    .parse(process.argv);

if (program.args.length !== 1) {
    logger.error('Invalid number of arguments. Usage: ./cli getAdmins <publicPath>');
    console.log(program.help());

} else {

    var publicPath = program.args[0];

    if (!util.pathRegExp.test(publicPath)) {
        logger.error(util.invalidPathError);

    } else { 

        db.getAdmins(publicPath, function(err, admins) {
            if (err) {
                logger.error(err);

            } else if (admins.length === 0) {
                logger.info('No administrators available for the service ' + publicPath);

            } else {
                console.log('SERVICE: ' + publicPath + ' ADMINISTRATORS:');
                for (var i = 0; i < admins.length; i++) {
                    console.log('   ' + admins[i]);
                }
            }
        });
    }
}