#!/usr/bin/env node

/* Copyright (c) 2015 - 2017 CoNWeT Lab., Universidad Politécnica de Madrid
 *
 * This file belongs to the Accounting Proxy
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

var async = require('async'),
    config = require('./../config'),
    program = require('commander'),
    logger = require('./../log');

var db = require(config.database.type);

db.init(function(err) {

    if (err) {
        logger.error(err);
    } else {

        program
            .description('Configuration tool for the accounting proxy')
            .version('0.0.2')
            .command('addService <publicPath> <URL> <applicationId> <httpMethod> [otherHttpMethods...]', 'add new service to accounting proxy')
            .command('getService', 'display service\'s information')
            .command('deleteService <publicPath>', 'delete the service from the accounting proxy')
            .command('addAdmin <userId>', 'add new administrator')
            .command('deleteAdmin <userId>', 'delete the specified admin')
            .command('bindAdmin <userId> <publicPath>', 'add a new administrator fot the service specified by the public path')
            .command('unbindAdmin <userId> <publicPath>', 'delete the specified administrator for the specified service by its public path')
            .command('getAdmins <publicPath>', 'display all the administrators for the specified service')
            .parse(process.argv);
    }
});