#!/usr/bin/env node

/* Copyright (c) 2015 - 2017 CoNWeT Lab., Universidad Politécnica de Madrid
 *
 * This file belongs to the Accounting Proxy
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

// Adds a new administrator.

var program = require('commander'),
    config = require('./../config'),
    logger = require('./../log');

var db = require(config.database.type);

program
    .description('Adds a new administrator.')
    .parse(process.argv);

if (program.args.length !== 1) {
    logger.error('Invalid number of arguments. Usage: ./cli addAdmin <userId>');
    console.log(program.help());

} else {

    var userId = program.args[0];

    db.addAdmin(userId, function(err) {
        if (err) {
            logger.error(err);
        } else {
            logger.info('Added admin: ' + userId);
        }
    });
}
