#!/usr/bin/env node

/* Copyright (c) 2015 - 2017 CoNWeT Lab., Universidad Politécnica de Madrid
 *
 * This file belongs to the Accounting Proxy
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

// If public path is specified, it returns the service URL, the application Id and the type of service. otherwise,
//  returns the information of all services.

var util = require('./../lib/util'),
    program = require('commander'),
    config = require('./../config'),
    logger = require('./../lib/log');

var db = config.getDatabase();

var printService = function (service) {
    var isCBService = service.isCBService === 0 ? 'no' : 'yes';
    console.log('PUBLIC PATH: ' + service.publicPath + ' URL: ' + service.url + ' APP-ID: ' + service.appId + ' CONTEXT-BROKER: ' + isCBService + ' METHODS: ' + service.methods);
};

program
    .option('-p, --public-path', 'only displays the information of the service specified')
    .description(
        'Displays the URL, the application ID and the type (Context Broker or not) of all registered services.')
    .parse(process.argv);

var publicPath = program.publicPath ? program.args[0] : false;

if (publicPath) {

    if (!util.pathRegExp.test(publicPath)) {
        logger.error(util.invalidPathError);
    } else {

        db.getService(publicPath, function (err, service) {

            if(err) {
                console.log(err);

            } else if (service === null) {
                console.log('No service avaliable for path: ' + publicPath);

            } else {
                printService(service);
            }
        });
    }

} else {

    db.getAllServices(function(err, services) {
        if (err) {
            logger.error(err);

        } else if (services.length === 0) {
            console.log('No service registered. Use: "addService "publicPath" "URL" to register a new service.');

        } else {
            for (var i = 0; i < services.length; i++) {
                printService(services[i]);
            }
        }
    });
}