#!/usr/bin/env node

/* Copyright (c) 2015 - 2017 CoNWeT Lab., Universidad Politécnica de Madrid
 *
 * This file belongs to the Accounting Proxy
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

// Binds the specified administrator to the service specified by its public path.

var program = require('commander'),
    config = require('./../config'),
    logger = require('./../lib/log'),
    util = require('./../lib/util');

var db = config.getDatabase();

program
    .description('Adds the specified administrator to the service specified by the public path.')
    .parse(process.argv);

if (program.args.length !== 2) {
    logger.error('Invalid number of arguments. Usage: ./cli bindAdmin <userId> <publicPath>');
    console.log(program.help());

} else {

    var userId = program.args[0];
    var publicPath = program.args[1];

    if (!util.pathRegExp.test(publicPath)) {
        logger.error(util.invalidPathError);

    } else {

        db.bindAdmin(userId, publicPath, function(err) {
            if (err) {
                logger.error(err);
            } else {
                logger.info('Admin ' + userId + ' added to service ' + publicPath);
            }
        });
    }
}